---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install npm node"
  become: true 
  apt:
    name: [npm,nodejs]
    state: latest
    update_cache: yes

- name: Install PM2 packages
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: copy index test page 
  become: true 
  copy:
    src: index.js
    dest: ~/web/index.js


- name: Start the weeb server 
  ansible.builtin.raw: pm2 start ~/web/index.js -f


